-- CreateEnum
CREATE TYPE "ReservationStatus" AS ENUM ('EATS_HOME', 'DOES_NOT_EAT_HOME', 'TIMEOUT', 'UNKNOWN');

-- CreateTable
CREATE TABLE "Reservation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "status" "ReservationStatus" NOT NULL DEFAULT 'UNKNOWN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Reservation_pkey" PRIMARY KEY ("id")
);
